/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agroludos.gui;

import agroludos.Agroludos;
import agroludos.db.user.ManagerSistema;
import agroludos.db.components.*;
import java.awt.*;
import javax.swing.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luciano
 */
public class JFrameMainSystem extends javax.swing.JFrame {

    private final ManagerSistema agro;
    // Scheda MANAGER
    private Manager[] listManager;
    private Competizione[] listManagerCompetizioni;
    private Optional[] listManagerCompetizioniOptional;
    // Scheda COMPETIZIONI
    private Competizione[] listCompetizioni;
    // Scheda OPTIONAL
    private Optional[] listOptional;
    // Scheda PARTECIPANTI
    private Partecipante[] listPartecipanti;
    private Competizione[] listPartecipanteCompetizioni;
    
    public JFrameMainSystem(ManagerSistema agroSysMan) {
        agro = agroSysMan;
        Shared.setDefaultLookAndFeel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelManager = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jListaManager = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListManagerCompetizioni = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jManagerOptionalList = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabelManagerOptionalPrice = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelManagerMail = new javax.swing.JLabel();
        jPanelCompetizioni = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCompetizioni = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jCheckInCorso = new javax.swing.JCheckBox();
        jCheckAnnullate = new javax.swing.JCheckBox();
        jCheckConcluse = new javax.swing.JCheckBox();
        jCompetizioneUtentiIscritti = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelCompetizionePrezzo = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelCompetizioneManagerNome = new javax.swing.JLabel();
        jLabelCompetizioneManagerMail = new javax.swing.JLabel();
        jPanelOptional = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListOptional = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jOptionalDescription = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jOptionalPrice = new javax.swing.JSpinner();
        jOptionalApply = new javax.swing.JButton();
        jOptionalCancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanelPartecipanti = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jUtenteNome = new javax.swing.JLabel();
        jUtenteCognome = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jUtenteIndirizzo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jUtenteNascita = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jUtenteSesso = new javax.swing.JLabel();
        jUtenteTesseraSan = new javax.swing.JLabel();
        jUtenteMail = new javax.swing.JLabel();
        jUtenteDataSrc = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jUtenteCertificatoSrc = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jListaUtentiIscrizioni = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListaUtenti = new javax.swing.JList();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(317, 441));

        jTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane.setName("jPanelPartecipanti"); // NOI18N
        jTabbedPane.setOpaque(true);
        jTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneStateChanged(evt);
            }
        });

        jPanelManager.setName("jPanelManager"); // NOI18N

        jLabel3.setText("Manager di competizione selezionato");

        jListaManager.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jListaManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaManagerActionPerformed(evt);
            }
        });

        jLabel4.setText("Lista delle sue competizioni");

        jListManagerCompetizioni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListManagerCompetizioniValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(jListManagerCompetizioni);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Optional attivati e prezzo"));

        jManagerOptionalList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jManagerOptionalListActionPerformed(evt);
            }
        });

        jLabel13.setText("Optional");

        jLabelManagerOptionalPrice.setText("--€");

        jLabel17.setText("Prezzo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jManagerOptionalList, 0, 190, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelManagerOptionalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jManagerOptionalList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelManagerOptionalPrice)
                    .addComponent(jLabel17))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel18.setText("E-mail del manager");

        jLabelManagerMail.setText("-");

        javax.swing.GroupLayout jPanelManagerLayout = new javax.swing.GroupLayout(jPanelManager);
        jPanelManager.setLayout(jPanelManagerLayout);
        jPanelManagerLayout.setHorizontalGroup(
            jPanelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jListaManager, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelManagerLayout.createSequentialGroup()
                        .addGroup(jPanelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 97, Short.MAX_VALUE))
                    .addGroup(jPanelManagerLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelManagerMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelManagerLayout.setVerticalGroup(
            jPanelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jListaManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanelManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabelManagerMail))
                .addContainerGap())
        );

        jTabbedPane.addTab("Manager", jPanelManager);

        jPanelCompetizioni.setName("jPanelCompetizioni"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Tutte le competizioni");

        jScrollPane1.setBackground(new java.awt.Color(255, 153, 153));

        jListCompetizioni.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tiro con l'arco (01/05/2014)", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListCompetizioni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCompetizioniValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListCompetizioni);

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("Iscritti alla competizione selezionata");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtra competizioni"));

        jCheckInCorso.setSelected(true);
        jCheckInCorso.setText("In corso");
        jCheckInCorso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckInCorsoActionPerformed(evt);
            }
        });

        jCheckAnnullate.setText("Annullate");
        jCheckAnnullate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckAnnullateActionPerformed(evt);
            }
        });

        jCheckConcluse.setSelected(true);
        jCheckConcluse.setText("Concluse");
        jCheckConcluse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckConcluseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckInCorso)
                        .addGap(45, 45, 45)
                        .addComponent(jCheckConcluse))
                    .addComponent(jCheckAnnullate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckInCorso)
                    .addComponent(jCheckConcluse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckAnnullate))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informazioni sulla competizione selezionata"));

        jLabel9.setText("Prezzo impostato");

        jLabelCompetizionePrezzo.setText("10€");

        jLabel23.setText("Manager");

        jLabelCompetizioneManagerNome.setText("Marco Rossi");

        jLabelCompetizioneManagerMail.setText("marco.rossi@agroludos.it");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCompetizioneManagerMail)
                    .addComponent(jLabelCompetizioneManagerNome)
                    .addComponent(jLabelCompetizionePrezzo))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelCompetizionePrezzo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabelCompetizioneManagerNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCompetizioneManagerMail))
        );

        javax.swing.GroupLayout jPanelCompetizioniLayout = new javax.swing.GroupLayout(jPanelCompetizioni);
        jPanelCompetizioni.setLayout(jPanelCompetizioniLayout);
        jPanelCompetizioniLayout.setHorizontalGroup(
            jPanelCompetizioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompetizioniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCompetizioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jCompetizioneUtentiIscritti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanelCompetizioniLayout.setVerticalGroup(
            jPanelCompetizioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompetizioniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCompetizioneUtentiIscritti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Competizioni", jPanelCompetizioni);

        jPanelOptional.setName("jPanelOptional"); // NOI18N

        jScrollPane2.setBackground(new java.awt.Color(255, 153, 153));

        jListOptional.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListOptionalValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListOptional);

        jLabel6.setText("Descrizione per l'optional:");

        jOptionalDescription.setColumns(20);
        jOptionalDescription.setRows(5);
        jOptionalDescription.setText("\n");
        jScrollPane3.setViewportView(jOptionalDescription);

        jLabel11.setText("Prezzo");

        jOptionalPrice.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));

        jOptionalApply.setText("Applica");
        jOptionalApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOptionalApplyActionPerformed(evt);
            }
        });

        jOptionalCancel.setText("Annulla");
        jOptionalCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOptionalCancelActionPerformed(evt);
            }
        });

        jLabel12.setText("<html>NOTA: ogni modifica fatta agli optional, si rifletterà su ogni competizione che verrà creata dal momento della modifica in poi.</html>");

        javax.swing.GroupLayout jPanelOptionalLayout = new javax.swing.GroupLayout(jPanelOptional);
        jPanelOptional.setLayout(jPanelOptionalLayout);
        jPanelOptionalLayout.setHorizontalGroup(
            jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOptionalLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOptionalLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(12, 12, 12))
                    .addGroup(jPanelOptionalLayout.createSequentialGroup()
                        .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanelOptionalLayout.createSequentialGroup()
                                .addComponent(jOptionalApply, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jOptionalCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelOptionalLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jOptionalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanelOptionalLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelOptionalLayout.setVerticalGroup(
            jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jOptionalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOptionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOptionalApply)
                    .addComponent(jOptionalCancel))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Optional", jPanelOptional);

        jPanelPartecipanti.setName("jPanelPartecipanti"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informazioni sul partecipante"));

        jLabel5.setText("Nome");

        jUtenteNome.setText("-");

        jUtenteCognome.setText("-");

        jLabel14.setText("Cognome");

        jUtenteIndirizzo.setText("-");

        jLabel16.setText("Indirizzo");
        jLabel16.setToolTipText("");

        jUtenteNascita.setText("-");

        jLabel20.setText("Data di nascita");

        jLabel22.setText("Sesso");

        jLabel25.setText("Tessera san.");

        jLabel27.setText("E-mail");

        jLabel29.setText("Data SRC");

        jUtenteSesso.setText("-");

        jUtenteTesseraSan.setText("-");

        jUtenteMail.setText("-");

        jUtenteDataSrc.setText("-");

        jUtenteCertificatoSrc.setColumns(20);
        jUtenteCertificatoSrc.setRows(5);
        jScrollPane4.setViewportView(jUtenteCertificatoSrc);

        jLabel30.setText("Certificato SRC");

        jListaUtentiIscrizioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaUtentiIscrizioniActionPerformed(evt);
            }
        });

        jLabel7.setText("Iscrizioni");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(43, 43, 43)
                                .addComponent(jUtenteDataSrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(61, 61, 61)
                                .addComponent(jUtenteMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(27, 27, 27)
                                .addComponent(jUtenteTesseraSan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(61, 61, 61)
                                .addComponent(jUtenteSesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(jUtenteNascita, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jUtenteIndirizzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(46, 46, 46)
                                .addComponent(jUtenteCognome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(64, 64, 64)
                                .addComponent(jUtenteNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jListaUtentiIscrizioni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jUtenteNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jUtenteCognome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jUtenteIndirizzo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jUtenteNascita, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jUtenteSesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jUtenteTesseraSan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jUtenteMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jUtenteDataSrc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jListaUtentiIscrizioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(252, 252, 252))
        );

        jListaUtenti.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListaUtentiValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(jListaUtenti);

        javax.swing.GroupLayout jPanelPartecipantiLayout = new javax.swing.GroupLayout(jPanelPartecipanti);
        jPanelPartecipanti.setLayout(jPanelPartecipantiLayout);
        jPanelPartecipantiLayout.setHorizontalGroup(
            jPanelPartecipantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPartecipantiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPartecipantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPartecipantiLayout.setVerticalGroup(
            jPanelPartecipantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPartecipantiLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Utenti", jPanelPartecipanti);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // <editor-fold defaultstate="collapsed" desc="Tutto ciò che riguarda i manager">
    private void ManagerLoadList() throws SQLException
    {
        Shared.CreateList(jListaManager, listManager = agro.getManagers());
    }
    private void ManagerSelected(int index) throws SQLException
    {
        if (index < 0) return;
        String mail = listManager[index].getMail();
        Shared.CreateList(jListManagerCompetizioni, listManagerCompetizioni =
                agro.getCompetizioni(mail));
        jLabelManagerMail.setText(mail);
    }
    private void ManagerSelectedCompetition(int index) throws SQLException
    {
        if (index < 0) return;
        listManagerCompetizioniOptional = agro.getCompetizioneOptional(listManagerCompetizioni[index].getId());
        Shared.CreateList(jManagerOptionalList, listManagerCompetizioniOptional);
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Tutto ciò che riguarda le competizioni">
    private void CompetizioniLoadList() throws SQLException
    {
        int filter = (jCheckInCorso.isSelected() ? 1 : 0) |
                (jCheckConcluse.isSelected() ? 2 : 0) |
                (jCheckAnnullate.isSelected() ? 4 : 0);
        listCompetizioni = agro.getCompetizioniMinimal(filter);
        Shared.CreateList(jListCompetizioni, listCompetizioni);
    }
    private void CompetizioniSelected(int index) throws SQLException
    {
        if (index < 0) return;
        Competizione c = agro.getCompetizione(listCompetizioni[index].getId());
        jLabelCompetizionePrezzo.setText(String.valueOf(c.getPrezzo()));
        jLabelCompetizioneManagerNome.setText(c.getManager().toString());
        jLabelCompetizioneManagerMail.setText(c.getManager().getMail());
        Shared.CreateList(jCompetizioneUtentiIscritti, agro.getPartecipanti(c.getId()));
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Tutto ciò che riguarda gli optional">
    /**
     * Ricarica completamente la scheda Optional
     * @throws SQLException 
     */
    void ReloadOpitonalTab() throws SQLException
    {
        listOptional = agro.getOptional();
        Shared.CreateList(jListOptional, listOptional);
    }
    /**
     * Aggiorna tutte le proprietà annesse ad uno specifico optional
     * @param index indice dell'optional selezionato
     * @throws SQLException 
     */
    void ReloadOptional(int index) throws SQLException
    {
        if (index < 0) return;
        jOptionalPrice.setValue(listOptional[index].getPrezzo());
        jOptionalDescription.setText(listOptional[index].getDescrizione());
    }
    /**
     * Scrive nel database i valori impostati dall'interfaccia
     * @param index indice dell'optional selezionato
     * @throws SQLException 
     */
    void UpdateOptional(int index) throws SQLException
    {
        if (index < 0) return;
        Optional opt = new Optional(listOptional[index].getNome(),
            jOptionalDescription.getText(),
            (float)jOptionalPrice.getValue());
        agro.setOptional(opt);
        listOptional[index] = opt;
        ReloadOptional(index);
    }
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Tutto ciò che riguarda gli utenti">
    /**
     * Inserisce nella lista, i nomi di tutti i partecipanti
     */
    void PartecipantiLoadList() throws SQLException
    {
        Shared.CreateList(jListaUtenti, listPartecipanti = agro.getPartecipantiMinimal());
    }
    void PartecipanteLoad(int index) throws SQLException
    {
        if (index < 0) return;
        Partecipante p = agro.getPartecipante(listPartecipanti[index].getMail());
        jUtenteNome.setText(p.getNome());
        jUtenteCognome.setText(p.getCognome());
        jUtenteIndirizzo.setText(p.getIndirizzo());
        jUtenteNascita.setText(p.getDataNascitaString());
        jUtenteSesso.setText(String.valueOf(p.getSesso()));
        jUtenteTesseraSan.setText(p.getTesseraSan());
        jUtenteMail.setText(p.getMail());
        jUtenteDataSrc.setText(p.getDataSrcString());
        jUtenteCertificatoSrc.setText(p.getSrc());
        
        int[] idCompetizioni = agro.getPartecipanteCompetizioni(p.getMail());
        listPartecipanteCompetizioni = new Competizione[idCompetizioni.length];
        for (int i = 0; i < idCompetizioni.length; i++)
            listPartecipanteCompetizioni[i] = agro.getCompetizione(idCompetizioni[i]);
        Shared.CreateList(jListaUtentiIscrizioni, listPartecipanteCompetizioni);
    }
    // </editor-fold>
    
    /**
     * Chiamata quando si cambia scheda
     */
    private void jTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneStateChanged
        Component c = jTabbedPane.getSelectedComponent();
        String name = c.getName();
        try
        {
            if (name == "jPanelManager")
                ManagerLoadList();
            if (name == "jPanelCompetizioni")
                CompetizioniLoadList();
            else if (name == "jPanelOptional")
                ReloadOpitonalTab();
            else if (name == "jPanelPartecipanti")
                PartecipantiLoadList();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare la pagina\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTabbedPaneStateChanged

    /**
     * Chiamata quando si seleziona un optional
     */
    private void jListOptionalValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListOptionalValueChanged
        try {
            ReloadOptional(jListOptional.getSelectedIndex());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare l'optional selezionato\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListOptionalValueChanged

    private void jOptionalApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOptionalApplyActionPerformed
        try {
            UpdateOptional(jListOptional.getSelectedIndex());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile applicare le modifiche\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jOptionalApplyActionPerformed

    private void jOptionalCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOptionalCancelActionPerformed
        try {
            ReloadOptional(jListOptional.getSelectedIndex());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile ricaricare gli optional\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jOptionalCancelActionPerformed

    private void jListaUtentiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListaUtentiValueChanged
        try {
            PartecipanteLoad(jListaUtenti.getSelectedIndex());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare il partecipante\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListaUtentiValueChanged

    private void jListaManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaManagerActionPerformed
        try {
            ManagerSelected(jListaManager.getSelectedIndex());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare la lista delle competizioni\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListaManagerActionPerformed

    private void jListManagerCompetizioniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListManagerCompetizioniValueChanged
        try {
            ManagerSelectedCompetition(jListManagerCompetizioni.getSelectedIndex());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare la lista degli optional\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListManagerCompetizioniValueChanged

    private void jManagerOptionalListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManagerOptionalListActionPerformed
        if (listManagerCompetizioniOptional != null)
        {
            float prezzo = listManagerCompetizioniOptional[jManagerOptionalList.getSelectedIndex()].getPrezzo();
            jLabelManagerOptionalPrice.setText(String.valueOf(prezzo));
        }
    }//GEN-LAST:event_jManagerOptionalListActionPerformed

    private void jListaUtentiIscrizioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaUtentiIscrizioniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jListaUtentiIscrizioniActionPerformed

    private void jCheckInCorsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckInCorsoActionPerformed
        try {
            CompetizioniLoadList();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare la lista delle competizioni\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckInCorsoActionPerformed

    private void jCheckConcluseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckConcluseActionPerformed
        try {
            CompetizioniLoadList();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare la lista delle competizioni\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckConcluseActionPerformed

    private void jCheckAnnullateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckAnnullateActionPerformed
        try {
            CompetizioniLoadList();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare la lista delle competizioni\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jCheckAnnullateActionPerformed

    private void jListCompetizioniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCompetizioniValueChanged
        try {
            CompetizioniSelected(jListCompetizioni.getSelectedIndex());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare la competizione selezionata\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListCompetizioniValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMainSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMainSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMainSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMainSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new JFrameMainSystem((ManagerSistema)Agroludos.Connect(null).Login("a", "a")).setVisible(true);
            } catch (Exception ex) {
                Shared.showError(ex.toString());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckAnnullate;
    private javax.swing.JCheckBox jCheckConcluse;
    private javax.swing.JCheckBox jCheckInCorso;
    private javax.swing.JComboBox jCompetizioneUtentiIscritti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCompetizioneManagerMail;
    private javax.swing.JLabel jLabelCompetizioneManagerNome;
    private javax.swing.JLabel jLabelCompetizionePrezzo;
    private javax.swing.JLabel jLabelManagerMail;
    private javax.swing.JLabel jLabelManagerOptionalPrice;
    private javax.swing.JList jListCompetizioni;
    private javax.swing.JList jListManagerCompetizioni;
    private javax.swing.JList jListOptional;
    private javax.swing.JComboBox jListaManager;
    private javax.swing.JList jListaUtenti;
    private javax.swing.JComboBox jListaUtentiIscrizioni;
    private javax.swing.JComboBox jManagerOptionalList;
    private javax.swing.JButton jOptionalApply;
    private javax.swing.JButton jOptionalCancel;
    private javax.swing.JTextArea jOptionalDescription;
    private javax.swing.JSpinner jOptionalPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelCompetizioni;
    private javax.swing.JPanel jPanelManager;
    private javax.swing.JPanel jPanelOptional;
    private javax.swing.JPanel jPanelPartecipanti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextArea jUtenteCertificatoSrc;
    private javax.swing.JLabel jUtenteCognome;
    private javax.swing.JLabel jUtenteDataSrc;
    private javax.swing.JLabel jUtenteIndirizzo;
    private javax.swing.JLabel jUtenteMail;
    private javax.swing.JLabel jUtenteNascita;
    private javax.swing.JLabel jUtenteNome;
    private javax.swing.JLabel jUtenteSesso;
    private javax.swing.JLabel jUtenteTesseraSan;
    // End of variables declaration//GEN-END:variables
}
