/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agroludos.gui;

import agroludos.Agroludos;
import agroludos.DeniedRequestException;
import agroludos.FrontController;
import agroludos.InternalErrorException;
import agroludos.RequestNotSupportedException;
import agroludos.db.components.*;
import agroludos.db.exception.*;
import agroludos.db.user.ManagerCompetizione;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Luciano
 */
public final class JFrameManComp extends javax.swing.JFrame {

    FrontController fc;
    Competizione[] listCompetizioni;
    Partecipante[] listPartecipanti;
    
    public JFrameManComp(FrontController fc) 
    {
        this.fc=fc;
        Shared.setDefaultLookAndFeel();
        initComponents();
        LoadListCompetizioni();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCompetizioni = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonApplica = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabelPartecCur = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPartecMin = new javax.swing.JSpinner();
        jPartecMax = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jCompPrezzo = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jOptional1nome = new javax.swing.JCheckBox();
        jOptional3nome = new javax.swing.JCheckBox();
        jOptional2nome = new javax.swing.JCheckBox();
        jLabelOptional1Prezzo = new javax.swing.JLabel();
        jLabelOptional2Prezzo = new javax.swing.JLabel();
        jLabelOptional3Prezzo = new javax.swing.JLabel();
        jButtonAnnulla = new javax.swing.JButton();
        jButtonCreaCompetizione = new javax.swing.JButton();
        jButtonAnnullaCompetizione = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPartecipanti = new javax.swing.JList();
        jButtonCancellaPartecipante = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jUtenteNome = new javax.swing.JLabel();
        jUtenteCognome = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jUtenteIndirizzo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jUtenteNascita = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jUtenteSesso = new javax.swing.JLabel();
        jUtenteTesseraSan = new javax.swing.JLabel();
        jUtenteMail = new javax.swing.JLabel();
        jUtenteDataSrc = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jUtenteCertificatoSrc = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager di competizione");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Le tue competizioni"));

        jListCompetizioni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListCompetizioniValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListCompetizioni);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Modifiche competizione"));

        jLabel3.setText("Partecipanti");

        jButtonApplica.setText("Applica");
        jButtonApplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplicaActionPerformed(evt);
            }
        });

        jLabel12.setText("Prezzo competizione");

        jLabelPartecCur.setText("0");

        jLabel13.setText("Minimo partecipanti");

        jLabel6.setText("/");

        jCompPrezzo.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(1.0f), Float.valueOf(100.0f), Float.valueOf(0.5f)));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Scelta optional"));

        jOptional1nome.setText("Colazione");

        jOptional3nome.setText("Pernotto");

        jOptional2nome.setText("Pranzo");

        jLabelOptional1Prezzo.setText("-");

        jLabelOptional2Prezzo.setText("-");

        jLabelOptional3Prezzo.setText("-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jOptional3nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelOptional3Prezzo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jOptional2nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelOptional2Prezzo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jOptional1nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelOptional1Prezzo)))
                .addGap(39, 39, 39))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOptional1nome)
                    .addComponent(jLabelOptional1Prezzo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOptional2nome)
                    .addComponent(jLabelOptional2Prezzo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOptional3nome)
                    .addComponent(jLabelOptional3Prezzo)))
        );

        jButtonAnnulla.setLabel("Annulla ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonApplica, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnnulla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPartecMax, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPartecMin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCompPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(53, 53, 53)
                                .addComponent(jLabelPartecCur)
                                .addGap(81, 81, 81))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelPartecCur)
                    .addComponent(jPartecMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPartecMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCompPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApplica)
                    .addComponent(jButtonAnnulla)))
        );

        jButtonCreaCompetizione.setText("Crea competizione");
        jButtonCreaCompetizione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreaCompetizioneActionPerformed(evt);
            }
        });

        jButtonAnnullaCompetizione.setText("Annulla competizione");
        jButtonAnnullaCompetizione.setActionCommand("Elimina competizione");
        jButtonAnnullaCompetizione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnullaCompetizioneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonAnnullaCompetizione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCreaCompetizione, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCreaCompetizione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnnullaCompetizione)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Gli utenti iscritti"));

        jListPartecipanti.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListPartecipantiValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListPartecipanti);

        jButtonCancellaPartecipante.setText("Cancella partecipante");
        jButtonCancellaPartecipante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancellaPartecipanteActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informazioni sul partecipante"));

        jLabel5.setText("Nome");

        jUtenteNome.setText("-");
        jUtenteNome.setMaximumSize(new java.awt.Dimension(135, 14));
        jUtenteNome.setMinimumSize(new java.awt.Dimension(135, 14));
        jUtenteNome.setPreferredSize(new java.awt.Dimension(135, 14));

        jUtenteCognome.setText("-");
        jUtenteCognome.setMaximumSize(new java.awt.Dimension(135, 14));
        jUtenteCognome.setMinimumSize(new java.awt.Dimension(135, 14));
        jUtenteCognome.setPreferredSize(new java.awt.Dimension(135, 14));

        jLabel14.setText("Cognome");

        jUtenteIndirizzo.setText("-");
        jUtenteIndirizzo.setMaximumSize(new java.awt.Dimension(135, 14));
        jUtenteIndirizzo.setMinimumSize(new java.awt.Dimension(135, 14));
        jUtenteIndirizzo.setPreferredSize(new java.awt.Dimension(135, 14));

        jLabel16.setText("Indirizzo");
        jLabel16.setToolTipText("");

        jUtenteNascita.setText("-");
        jUtenteNascita.setMaximumSize(new java.awt.Dimension(135, 14));
        jUtenteNascita.setMinimumSize(new java.awt.Dimension(135, 14));
        jUtenteNascita.setPreferredSize(new java.awt.Dimension(135, 14));

        jLabel20.setText("Data di nascita");

        jLabel22.setText("Sesso");

        jLabel25.setText("Tessera san.");

        jLabel27.setText("E-mail");

        jLabel29.setText("Data SRC");

        jUtenteSesso.setText("-");
        jUtenteSesso.setMaximumSize(new java.awt.Dimension(135, 14));
        jUtenteSesso.setMinimumSize(new java.awt.Dimension(135, 14));
        jUtenteSesso.setPreferredSize(new java.awt.Dimension(135, 14));

        jUtenteTesseraSan.setText("-");
        jUtenteTesseraSan.setMaximumSize(new java.awt.Dimension(135, 14));
        jUtenteTesseraSan.setMinimumSize(new java.awt.Dimension(135, 14));
        jUtenteTesseraSan.setPreferredSize(new java.awt.Dimension(135, 14));

        jUtenteMail.setText("-");
        jUtenteMail.setMaximumSize(new java.awt.Dimension(135, 14));
        jUtenteMail.setMinimumSize(new java.awt.Dimension(135, 14));
        jUtenteMail.setPreferredSize(new java.awt.Dimension(135, 14));

        jUtenteDataSrc.setText("-");
        jUtenteDataSrc.setMaximumSize(new java.awt.Dimension(135, 14));
        jUtenteDataSrc.setMinimumSize(new java.awt.Dimension(135, 14));
        jUtenteDataSrc.setPreferredSize(new java.awt.Dimension(135, 14));

        jUtenteCertificatoSrc.setColumns(20);
        jUtenteCertificatoSrc.setRows(5);
        jScrollPane4.setViewportView(jUtenteCertificatoSrc);

        jLabel30.setText("Certificato SRC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(43, 43, 43)
                                .addComponent(jUtenteDataSrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(61, 61, 61)
                                .addComponent(jUtenteMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(27, 27, 27)
                                .addComponent(jUtenteTesseraSan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(61, 61, 61)
                                .addComponent(jUtenteSesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jUtenteIndirizzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(46, 46, 46)
                                .addComponent(jUtenteCognome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(jUtenteNascita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(64, 64, 64)
                                .addComponent(jUtenteNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jUtenteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jUtenteCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jUtenteIndirizzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jUtenteNascita, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jUtenteSesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jUtenteTesseraSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jUtenteMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jUtenteDataSrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCancellaPartecipante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancellaPartecipante)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void LoadListCompetizioni()
    {
        try 
        {
            listCompetizioni = (Competizione[])fc.processRequest(FrontController.Request.GetCompetizioni,null);
            Shared.CreateList(jListCompetizioni,(Object []) listCompetizioni);
        }
        catch (DeniedRequestException | RequestNotSupportedException | InternalErrorException e)
        {
            Shared.showError(this, e.toString());
        }
        
    }
    void SelezionaCompetizione(int index) throws SQLException
    {
        if (index < 0) return;
        try
        {
        //Competizione c = agro.getCompetizione(listCompetizioni[index].getId());
        //Optional [] opt=agro.getOptional();
        Competizione c=(Competizione)fc.processRequest(FrontController.Request.GetCompetizioneFromId,new Object[] {listCompetizioni[index].getId()})[0];
        int IdC=(int)fc.processRequest(FrontController.Request.GetIdFromCompetizione,new Object []{c})[0];
        //Optional [] opt=(Optional[])fc.processRequest(FrontController.Request.GetCompetizioneOptionals,new Object []{c.getId()});
        Optional [] opt=(Optional[])fc.processRequest(FrontController.Request.GetOptional,null);
        jLabelPartecCur.setText(String.valueOf(c.getNPart()));
        jPartecMax.setValue(c.getNMax());
        jPartecMin.setValue(c.getNMin());
        jCompPrezzo.setValue((int)c.getPrezzo());
        jOptional1nome.setSelected(false);
        jOptional2nome.setSelected(false);
        jOptional3nome.setSelected(false);
        jLabelOptional1Prezzo.setText(String.valueOf(opt[0].getPrezzo())+"€");
        jLabelOptional2Prezzo.setText(String.valueOf(opt[1].getPrezzo())+"€");
        jLabelOptional3Prezzo.setText(String.valueOf(opt[2].getPrezzo())+"€");
        for (Optional o : (Optional[])fc.processRequest(FrontController.Request.GetCompetizioneOptionals,new Object []{IdC}))
        {
            if (jOptional1nome.getText().compareTo(o.getNome()) == 0)
                jOptional1nome.setSelected(true);
            else if (jOptional2nome.getText().compareTo(o.getNome()) == 0)
                jOptional2nome.setSelected(true);
                
                
            else if (jOptional3nome.getText().compareTo(o.getNome()) == 0)
                 jOptional3nome.setSelected(true);
                
        }
        
        //listPartecipanti = agro.getPartecipanti(c.getId());
        int idC=(int)fc.processRequest(FrontController.Request.GetIdFromCompetizione,new Object[]{c})[0];
        listPartecipanti=(Partecipante [])fc.processRequest(FrontController.Request.GetPartecipantiCompetizione,new Object []{idC});
        Shared.CreateList(jListPartecipanti,(Object []) listPartecipanti);
        }
        catch (DeniedRequestException | RequestNotSupportedException | InternalErrorException e)
        {
            Shared.showError(this, e.toString());
        }
    }
    void PartecipanteLoad(int index) throws SQLException
    {
        if (index < 0) return;
        try
        {
        //Partecipante p = agro.getPartecipante(listPartecipanti[index].getMail());
        String PMail=(String)fc.processRequest(FrontController.Request.GetMailFromPartecipante,new Object[]{listPartecipanti[index]})[0];
        Partecipante p=(Partecipante) fc.processRequest(FrontController.Request.GetPartecipante,new Object []{PMail})[0];
        jUtenteNome.setText(p.getNome());
        jUtenteCognome.setText(p.getCognome());
        jUtenteIndirizzo.setText(p.getIndirizzo());
        jUtenteNascita.setText(p.getDataNascitaString());
        jUtenteSesso.setText(String.valueOf(p.getSesso()));
        jUtenteTesseraSan.setText(p.getTesseraSan());
        jUtenteMail.setText(p.getMail());
        jUtenteDataSrc.setText(p.getDataSrcString());
        jUtenteCertificatoSrc.setText(p.getSrc());
        }
        catch (DeniedRequestException | RequestNotSupportedException | InternalErrorException e)
        {
            Shared.showError(this, e.toString());
        }
    }
    
    private void jButtonCreaCompetizioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreaCompetizioneActionPerformed
        JFrame jFrame = new JFrameCreaComp(agro);
        jFrame.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCreaCompetizioneActionPerformed

    private void jButtonAnnullaCompetizioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnullaCompetizioneActionPerformed
        if (jListCompetizioni.getSelectedIndex() < 0)
            return;
        if (JOptionPane.showConfirmDialog(this,
                "La competizione da te creata sta per essere annullata. Una volta confermato, non sarà più possibile recuperarla. Sei sicuro di voler continuare?",
                "Conferma annullamento competizione",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) ==
                JOptionPane.YES_OPTION)
        {
            try {
                agro.annullaCompetizione(jListCompetizioni.getSelectedIndex());
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile annullare la competizione\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
            }
            LoadListCompetizioni();
        }
    }//GEN-LAST:event_jButtonAnnullaCompetizioneActionPerformed

    private void jListCompetizioniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListCompetizioniValueChanged
        try {
            SelezionaCompetizione(jListCompetizioni.getSelectedIndex());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare la competizione selezionata\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListCompetizioniValueChanged

    private void jButtonApplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplicaActionPerformed
        try 
        {
            Competizione c = agro.getCompetizione(listCompetizioni[jListCompetizioni.getSelectedIndex()].getId());
            if (agro.isModificaScaduto(c))
                throw new ModificaCompScadutaException();
            float prezzo_mod = Float.parseFloat(jCompPrezzo.getValue().toString());
            if ((int)jPartecMax.getValue()!=c.getNMax())
                agro.setNPartMax(c.getId(), (int)jPartecMax.getValue());
            if ((int)jPartecMin.getValue()!=c.getNMin())
                agro.setNPartMin(c.getId(),(int)jPartecMin.getValue());
            if (prezzo_mod!=c.getPrezzo())
                agro.setPrezzoComp(c.getId(),prezzo_mod);
            Optional [] opt_c=agro.getOptional(c.getId());
            boolean opt [] =new boolean [3];
            int nOpt=0;
            if (jOptional1nome.isSelected())
            {
                nOpt++;
                opt[0]=true;
            }
            else opt[0]=false;
            if (jOptional2nome.isSelected())
            {
                nOpt++;
                opt[1]=true;
            }
            else opt[1]=false;
            if (jOptional3nome.isSelected())
            {
                nOpt++;
                opt[2]=true;
            }
            else opt[2]=false;
            String optional_nome;
            for (int i=0;i<3;i++)
            {
                switch (i)
                {
                    case 0:
                        optional_nome="Colazione";
                        break;
                    case 1:
                        optional_nome="Pranzo";
                        break;
                    case 2:
                        optional_nome="Pernotto";
                        break;
                    default:
                        optional_nome="";
                        break;
                }
                if (opt[i])
                    agro.setOptionalCompetizione(c,agro.getOptional(optional_nome));
                else
                    agro.dropOptionalCompetizione(c,agro.getOptional(optional_nome));
            }
                        JOptionPane.showMessageDialog(null, "Modifica effettuata\ncon successo!\n"
                        , "Successo", JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Impossibile modificare la competizione selezionata" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
        catch (ModificaCompScadutaException ex)
        {
            JOptionPane.showMessageDialog(null,
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
        finally
        {
            JFrame jFrame=new JFrameManComp(agro);
            this.setVisible(false);
            jFrame.pack();
            jFrame.setVisible(true);
        }
    }//GEN-LAST:event_jButtonApplicaActionPerformed

    private void jListPartecipantiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListPartecipantiValueChanged
        try {
            PartecipanteLoad(jListPartecipanti.getSelectedIndex());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile caricare le informazioni dell'utente selezionato." +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jListPartecipantiValueChanged

    private void jButtonCancellaPartecipanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancellaPartecipanteActionPerformed
        // TODO add your handling code here:
        
        try 
        {
            if (jListPartecipanti.getSelectedIndex()!=-1)
                        if (JOptionPane.showConfirmDialog(this,
                "Il partecipante da te selezionato sta per essere annullato. Sei sicuro di voler continuare?",
                "Conferma annullamento competizione",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) ==
                JOptionPane.YES_OPTION)
                agro.dropPrenotazione(agro.getCompetizione(listCompetizioni[jListCompetizioni.getSelectedIndex()].getId()), agro.getPartecipante(listPartecipanti[jListPartecipanti.getSelectedIndex()].getMail()));
                JOptionPane.showMessageDialog(null, "Annullamento effettuato\ncon successo!\n"
                        , "Successo", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Impossibile annullare la prenotazione." +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
        finally
        {
            JFrame jFrame=new JFrameManComp(agro);
            this.setVisible(false);
            jFrame.pack();
            jFrame.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCancellaPartecipanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameManComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameManComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameManComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameManComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> {
            try {
                new JFrameManComp((ManagerCompetizione)Agroludos.Connect(null).Login("luciano.ciccariello@agroludos.it", "Xeey")).setVisible(true);
            } catch (Exception ex) {
                Shared.showError(null, ex.toString());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulla;
    private javax.swing.JButton jButtonAnnullaCompetizione;
    private javax.swing.JButton jButtonApplica;
    private javax.swing.JButton jButtonCancellaPartecipante;
    private javax.swing.JButton jButtonCreaCompetizione;
    private javax.swing.JSpinner jCompPrezzo;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelOptional1Prezzo;
    private javax.swing.JLabel jLabelOptional2Prezzo;
    private javax.swing.JLabel jLabelOptional3Prezzo;
    private javax.swing.JLabel jLabelPartecCur;
    private javax.swing.JList jListCompetizioni;
    private javax.swing.JList jListPartecipanti;
    private javax.swing.JCheckBox jOptional1nome;
    private javax.swing.JCheckBox jOptional2nome;
    private javax.swing.JCheckBox jOptional3nome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jPartecMax;
    private javax.swing.JSpinner jPartecMin;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jUtenteCertificatoSrc;
    private javax.swing.JLabel jUtenteCognome;
    private javax.swing.JLabel jUtenteDataSrc;
    private javax.swing.JLabel jUtenteIndirizzo;
    private javax.swing.JLabel jUtenteMail;
    private javax.swing.JLabel jUtenteNascita;
    private javax.swing.JLabel jUtenteNome;
    private javax.swing.JLabel jUtenteSesso;
    private javax.swing.JLabel jUtenteTesseraSan;
    // End of variables declaration//GEN-END:variables
}
