package agroludos.gui;

import agroludos.*;
import agroludos.db.*;
import agroludos.db.exception.WrongLoginException;
import agroludos.db.user.Anonimo;
import agroludos.db.user.ManagerCompetizione;
import agroludos.db.user.ManagerSistema;
import agroludos.db.user.Utente;
import java.sql.SQLException;
import javax.swing.*;

/**
 *
 * @author Luciano
 */
public class JFrameLogin extends javax.swing.JFrame {

    FrontController fc;
    
    public JFrameLogin(FrontController fc)
    {
        this.fc = fc;
        Shared.setDefaultLookAndFeel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextMail = new javax.swing.JTextField();
        jLoginMail = new javax.swing.JLabel();
        jLoginPassword = new javax.swing.JLabel();
        jLoginEntra = new javax.swing.JButton();
        jLoginRegistrati = new javax.swing.JButton();
        jTextPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agroludos");

        jLoginMail.setText("Nome utente");

        jLoginPassword.setText("Password");

        jLoginEntra.setText("Entra");
        jLoginEntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginEntraActionPerformed(evt);
            }
        });

        jLoginRegistrati.setText("Registrati");
        jLoginRegistrati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginRegistratiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLoginMail)
                            .addComponent(jLoginPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextMail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLoginRegistrati)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLoginEntra, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLoginMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginPassword)
                    .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginRegistrati)
                    .addComponent(jLoginEntra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginEntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginEntraActionPerformed
        try
        {
            fc.processRequest(FrontController.Request.Login,
                    new String[]{jTextMail.getText(), jTextPassword.getText()});
        }
        catch (DeniedRequestException | RequestNotSupportedException | InternalErrorException e)
        {
            Shared.showError(this, e.toString());
        }
    }//GEN-LAST:event_jLoginEntraActionPerformed

    private void jLoginRegistratiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginRegistratiActionPerformed
        try
        {
            fc.processRequest(FrontController.Request.FrameRegistrazione, null);
        }
        catch (DeniedRequestException | RequestNotSupportedException | InternalErrorException e)
        {
            Shared.showError(this, e.toString());
        }
    }//GEN-LAST:event_jLoginRegistratiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jLoginEntra;
    private javax.swing.JLabel jLoginMail;
    private javax.swing.JLabel jLoginPassword;
    private javax.swing.JButton jLoginRegistrati;
    private javax.swing.JTextField jTextMail;
    private javax.swing.JPasswordField jTextPassword;
    // End of variables declaration//GEN-END:variables
}
