/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package agroludos;

import agroludos.db.*;
import agroludos.db.components.CampiVuotiException;
import agroludos.db.components.Competizione;
import agroludos.db.components.Optional;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Luciano
 */
public class JFrameHomePartec extends javax.swing.JFrame
{
    AgroPartec agro;
    Competizione [] listComp;
    Optional [] listOpt;
 
    public JFrameHomePartec()
    {
        initComponents();
        agro=null;
 
    }

    public JFrameHomePartec(AgroPartec agro)
    {
        try 
        {
            initComponents();
            this.agro=agro;
            CompetizioniDisponibiliLoadList();
        } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, "Impossibile caricare le competizioni\n" +
                    ex.toString(), "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    void CompetizioniDisponibiliLoadList() throws SQLException
    {
        CreateList(jListDisponibili,listComp=agro.getCompetizioniDisponibili());
    }

    void CreateList(JList jList, Object[] list)
    {
        DefaultListModel listModel = new DefaultListModel();
        jList.removeAll();
        for (Object o : list)
        {
            listModel.addElement(o.toString());
        }
        jList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabelNPart = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelMailMC = new javax.swing.JLabel();
        jLabelPrezzo_Comp = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabelMC = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabelPrezzoTot = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDisponibili = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jCheckBoxOpt1 = new javax.swing.JCheckBox();
        jCheckBoxOpt3 = new javax.swing.JCheckBox();
        jCheckBoxOpt2 = new javax.swing.JCheckBox();
        jLabelPrezzoOpt1 = new javax.swing.JLabel();
        jLabelPrezzoOpt2 = new javax.swing.JLabel();
        jLabelPrezzoOpt3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMyIscrizioni = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabelMyPartecipante = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelMyCosto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxMyOptional1 = new javax.swing.JCheckBox();
        jCheckBoxMyOptional3 = new javax.swing.JCheckBox();
        jCheckBoxMyOptional2 = new javax.swing.JCheckBox();
        jLabelMyOptionalCosto1 = new javax.swing.JLabel();
        jLabelMyOptionalCosto2 = new javax.swing.JLabel();
        jLabelMyOptionalCosto3 = new javax.swing.JLabel();
        jButtonMyOptionalConferma = new javax.swing.JButton();
        jButtonMyOptionalAnnulla = new javax.swing.JButton();
        jLabelMyManagerMail = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelMyManagerNome = new javax.swing.JLabel();
        jButtonMyAnnullaIscrizione = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelMyPrezzoTotale = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Posti rimanenti");
        jLabel7.setToolTipText("");

        jLabelNPart.setText("28");

        jLabel12.setText("Costo competizione");

        jLabelMailMC.setText("marco.rossi@agroludos.it");

        jLabelPrezzo_Comp.setText("10€");

        jLabel26.setText("Manager");

        jLabelMC.setText("Marco Rossi");

        jButton7.setText("Iscriviti alla competizione");

        jLabel17.setText("Prezzo totale");

        jLabelPrezzoTot.setText("10€");

        jListDisponibili.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tiro con l'arco (DATA)", "Corsa campestre (GG/MM/AAAA)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListDisponibili.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListDisponibiliValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListDisponibili);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Scelta optional"));

        jCheckBoxOpt1.setText("Colazione");

        jCheckBoxOpt3.setText("Pernotto");

        jCheckBoxOpt2.setText("Pranzo");

        jLabelPrezzoOpt1.setText("5€");

        jLabelPrezzoOpt2.setText("10€");

        jLabelPrezzoOpt3.setText("25€");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxOpt1)
                    .addComponent(jCheckBoxOpt2)
                    .addComponent(jCheckBoxOpt3))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrezzoOpt2)
                    .addComponent(jLabelPrezzoOpt1)
                    .addComponent(jLabelPrezzoOpt3))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxOpt1)
                    .addComponent(jLabelPrezzoOpt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxOpt2)
                    .addComponent(jLabelPrezzoOpt2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxOpt3)
                    .addComponent(jLabelPrezzoOpt3)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabelNPart))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelPrezzo_Comp))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelPrezzoTot))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMailMC)
                                    .addComponent(jLabelMC)))
                            .addComponent(jLabel26))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelNPart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabelPrezzo_Comp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabelPrezzoTot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabelMC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMailMC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Competizioni disponibili", jPanel2);

        jListMyIscrizioni.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Tiro con l'arco (DATA)", "Corsa campestre (GG/MM/AAAA)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListMyIscrizioni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListMyIscrizioniValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListMyIscrizioni);

        jLabel1.setText("Partecipante");

        jLabelMyPartecipante.setText("#22");

        jLabel5.setText("Costo competizione");

        jLabelMyCosto.setText("10€");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifica optional"));

        jCheckBoxMyOptional1.setText("Colazione");

        jCheckBoxMyOptional3.setText("Pernotto");

        jCheckBoxMyOptional2.setText("Pranzo");

        jLabelMyOptionalCosto1.setText("5€");

        jLabelMyOptionalCosto2.setText("10€");

        jLabelMyOptionalCosto3.setText("25€");

        jButtonMyOptionalConferma.setText("Conferma");

        jButtonMyOptionalAnnulla.setText("Annulla");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonMyOptionalConferma, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMyOptionalAnnulla, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxMyOptional1)
                            .addComponent(jCheckBoxMyOptional2)
                            .addComponent(jCheckBoxMyOptional3))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMyOptionalCosto2)
                            .addComponent(jLabelMyOptionalCosto1)
                            .addComponent(jLabelMyOptionalCosto3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMyOptional1)
                    .addComponent(jLabelMyOptionalCosto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMyOptional2)
                    .addComponent(jLabelMyOptionalCosto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMyOptional3)
                    .addComponent(jLabelMyOptionalCosto3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMyOptionalConferma)
                    .addComponent(jButtonMyOptionalAnnulla)))
        );

        jLabelMyManagerMail.setText("marco.rossi@agroludos.it");

        jLabel23.setText("Manager");

        jLabelMyManagerNome.setText("Marco Rossi");

        jButtonMyAnnullaIscrizione.setText("Annulla iscrizione");

        jLabel2.setText("Prezzo totale");

        jLabelMyPrezzoTotale.setText("10€");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMyAnnullaIscrizione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabelMyPartecipante))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelMyCosto))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelMyPrezzoTotale))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMyManagerMail)
                                    .addComponent(jLabelMyManagerNome)))
                            .addComponent(jLabel23))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMyPartecipante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelMyCosto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelMyPrezzoTotale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabelMyManagerNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMyManagerMail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMyAnnullaIscrizione)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Le tue iscrizioni", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setMyPartecipanteId(int value)
    {
        jLabelMyPartecipante.setText("#" + Integer.toString(value));
    }
    void setCostoCompetizione(int value)
    {
        jLabelMyCosto.setText(Integer.toString(value) + "€");
    }
    void setMyOptional(int index, boolean value)
    {
        JCheckBox jCheckBox;
        switch (index)
        {
            case 0:
                jCheckBox = jCheckBoxMyOptional1;
                break;
            case 1:
                jCheckBox = jCheckBoxMyOptional2;
                break;
            case 2:
                jCheckBox = jCheckBoxMyOptional3;
                break;
            default:
                // caso non gestito
                return;
        }
        jCheckBox.setSelected(value);
    }
    void setMyOptionalPrice(int index, int value)
    {
        JLabel jLabel;
        switch (index)
        {
            case 0:
                jLabel = jLabelMyOptionalCosto1;
                break;
            case 1:
                jLabel = jLabelMyOptionalCosto2;
                break;
            case 2:
                jLabel = jLabelMyOptionalCosto3;
                break;
            default:
                // caso non gestito
                return;
        }
        jLabel.setText(Integer.toString(value) + "€");
    }
    void setMyTotalPrice(int value)
    {
        jLabelMyPrezzoTotale.setText(Integer.toString(value) + "€");
    }
    void setMyManagerName(String value)
    {
        jLabelMyManagerNome.setText(value);
    }
    void setMyManagerMail(String value)
    {
        jLabelMyManagerMail.setText(value);
    }
    int getTotalPrice()
    {
        int value = db.getCostoCompetizione();
        for (int i = 0; i < 3; i++)
            value += db.getOptionalPrezzo(i);
        return value;
    }
    
    private void jListMyIscrizioniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListMyIscrizioniValueChanged
        setMyPartecipanteId(db.getPartecipanteId());
        setCostoCompetizione(db.getCostoCompetizione());
        for (int i = 0; i < 3; i++)
        {
            setMyOptional(i, db.getOptionalScelti(i));
            setMyOptionalPrice(i, db.getOptionalPrezzo(i));
        }
        setMyTotalPrice(getTotalPrice());
        setMyManagerName(db.getManagerNome());
        setMyManagerMail(db.getManagerMail());
    }//GEN-LAST:event_jListMyIscrizioniValueChanged

    void CompetizioneLoad (int index) throws SQLException
    {
        Competizione c=agro.getCompetizione(listComp[index].getId());
        jLabelNPart.setText(String.valueOf(c.getNMax()-c.getNPart()));
        jLabelPrezzo_Comp.setText(String.valueOf(c.getPrezzo())+"€");
        jCheckBoxOpt1.setEnabled(false);
        jCheckBoxOpt2.setEnabled(false);
        jCheckBoxOpt3.setEnabled(false);
        jCheckBoxOpt1.setText("-");
        jCheckBoxOpt2.setText("-");
        jCheckBoxOpt3.setText("-");
        jLabelPrezzoOpt1.setText("-");
        jLabelPrezzoOpt2.setText("-");
        jLabelPrezzoOpt3.setText("-");
        Optional [] opt=c.getOptComp();
        if(opt!=null)
        {    
        for (int i=opt.length-1;i>=0;i--)
        {
            if(opt[i].getNome().compareTo("Colazione")==0)
            {
                jCheckBoxOpt1.setEnabled(true);
                jCheckBoxOpt1.setText(opt[i].getNome()); 
                jLabelPrezzoOpt1.setText(String.valueOf(opt[i].getPrezzo())+"€");
            }
            else if(opt[i].getNome().compareTo("Pranzo")==0)
                {  
                   jCheckBoxOpt2.setEnabled(true);
                   jCheckBoxOpt2.setText(opt[i].getNome()); 
                   jLabelPrezzoOpt2.setText(String.valueOf(opt[i].getPrezzo())+"€");
                }
                else
                {
                   jCheckBoxOpt3.setEnabled(true);
                   jCheckBoxOpt3.setText(opt[i].getNome()); 
                   jLabelPrezzoOpt3.setText(String.valueOf(opt[i].getPrezzo())+"€");
                }               
        }
        }
        jLabelPrezzoTot.setText(String.valueOf(c.getPrezzo()));
        jLabelMC.setText(c.getNomeMC()+" "+c.getCognomeMC());
        jLabelMailMC.setText(c.getEmailMC());
    }        
    private void jListDisponibiliValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListDisponibiliValueChanged
        try {
            // TODO add your handling code here:
            CompetizioneLoad(jListDisponibili.getSelectedIndex());
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHomePartec.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jListDisponibiliValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHomePartec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHomePartec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHomePartec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHomePartec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHomePartec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonMyAnnullaIscrizione;
    private javax.swing.JButton jButtonMyOptionalAnnulla;
    private javax.swing.JButton jButtonMyOptionalConferma;
    private javax.swing.JCheckBox jCheckBoxMyOptional1;
    private javax.swing.JCheckBox jCheckBoxMyOptional2;
    private javax.swing.JCheckBox jCheckBoxMyOptional3;
    private javax.swing.JCheckBox jCheckBoxOpt1;
    private javax.swing.JCheckBox jCheckBoxOpt2;
    private javax.swing.JCheckBox jCheckBoxOpt3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelMC;
    private javax.swing.JLabel jLabelMailMC;
    private javax.swing.JLabel jLabelMyCosto;
    private javax.swing.JLabel jLabelMyManagerMail;
    private javax.swing.JLabel jLabelMyManagerNome;
    private javax.swing.JLabel jLabelMyOptionalCosto1;
    private javax.swing.JLabel jLabelMyOptionalCosto2;
    private javax.swing.JLabel jLabelMyOptionalCosto3;
    private javax.swing.JLabel jLabelMyPartecipante;
    private javax.swing.JLabel jLabelMyPrezzoTotale;
    private javax.swing.JLabel jLabelNPart;
    private javax.swing.JLabel jLabelPrezzoOpt1;
    private javax.swing.JLabel jLabelPrezzoOpt2;
    private javax.swing.JLabel jLabelPrezzoOpt3;
    private javax.swing.JLabel jLabelPrezzoTot;
    private javax.swing.JLabel jLabelPrezzo_Comp;
    private javax.swing.JList jListDisponibili;
    private javax.swing.JList jListMyIscrizioni;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
